AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  lambda-websocket
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaAWSSAMPoc_OnConnect # Nome do lambda que será criado - Exemplo: lmb-hub-websocket-on-connect
      CodeUri: connect/
      Handler: on_connect_lambda.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      MemorySize: 128
  DisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaAWSSAMPoc_OnDisconnect # Nome do lambda que será criado - Exemplo: lmb-hub-websocket-on-disconnect
      CodeUri: disconnect/
      Handler: on_disconnect_lambda.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      MemorySize: 128
  MessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaAWSSAMPoc_MessageSender # Nome do lambda que será criado - Exemplo: lmb-hub-websocket-on-send-message
      CodeUri: message/
      Handler: on_send_message_lambda.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      MemorySize: 128
